FROM python:3.9


WORKDIR /app

COPY data/dev_data data/dev_data/
COPY api/requirements.txt  api/.flaskenv api/
COPY api/api.py api/LanguageModel.py api/__init__.py api/

RUN pip install -r ./api/requirements.txt
RUN pip install gunicorn
ENV FLASK_ENV production
ENV OPENAI_API_KEY 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

EXPOSE 5001
CMD ["gunicorn", "-b", ":5001", "api.api:app", "--timeout 0"]
#CMD ["bash"]