services:
  api:
    # TODO fix env variables for compose yaml
    # TODO make project id a variable
   # env_file:
      #- .env
    build:
      context: .
      dockerfile: Dockerfile.api
    image: gcr.io/animated-verve-240319/react-flask-app-api
    # ports:
      # - "5001:5001"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: gcr.io/animated-verve-240319/react-flask-app-client
    ports:
      - "3000:80"
